config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :events, only: %i[show new create update] do
      resources :messages, only: %i[create]
      resources :event_users, only: %i[new]
    end
    resources :usergroups, only: %i[new create destroy] do
      member do
        delete :kick
      end
    end
  end
  resources :events, only: %i[index destroy]
  resources :usergroups, only: %i[index] do
    member do
      put :accept
    end
  end
  resources :event_users, only: %i[index destroy create] do
    member do
      put :accept
    end
  end
  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end
  resources :friendships, only: %i[index destroy] do
    member do
      put :accept
    end
  end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, presence: true

  def users
    EventUser.all.map(&:user)
  end
end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController
  def index
    @event_users = EventUser.where('user_id = ? AND status = ?', current_user.id, true)
    if @event_users.size > 0
      @event_users = @event_users.reject { |event| event.event.end_date <= Date.today }
      @event_users = @event_users.sort_by { |event| event.event.end_date } if @event_users.size > 0
    end
    @myusergroups = UserGroup.where('user_id = ? AND status = ?', current_user.id, true)
    @groups = []
    @myusergroups.each do |ug|
      @groups << Group.find(ug.group_id)
    end
    @events = []
    @groups.each do |ug|
      Event.where('group_id = ?', ug.id).each do |event|
        @events << event
      end
    end
    @event_users.each do |eu|
      @events << eu.event
    end
    if @events.length > 0
      @events.reject! { |event| event.end_date <= Date.today }
      @events.sort_by! { |event| event.end_date } if @events.length > 0
    end
  end

  def new
    @event_user = EventUser.new
    @event = Event.find(params[:event_id])
    @group = Group.find(@event.group_id)
  end

  def create
    @event = Event.find(params[:format])
    @group = Group.find(@event.group_id)
    params[:event_user][:user_id].select { |i| i != "" }.each do |id|
      @eventuser = EventUser.new
      @user = User.find(id)
      @eventuser.event = @event
      @eventuser.user = @user
      unless @eventuser.save
        render :new
      end
    end
    redirect_to "/groups/#{@event.id}/events/#{@group.id}"
  end

  def accept
    @eventuser = EventUser.find(params[:id])
    @eventuser.status = true
    if @eventuser.save
      redirect_to "/groups/#{@eventuser.event.id}/events/#{@eventuser.event.group.id}"
    else
      render :index
    end
  end

  def destroy
    @eventuser = EventUser.find(params[:id])
    @eventuser.destroy
    if @eventuser.user_id == current_user.id
      redirect_to "/"
    else
      redirect_to "/groups/#{@eventuser.event.id}/events/#{@eventuser.event.group.id}"
    end
  end
end

app/views/event_users/_form.html.erb
<div class="container">
  <%= simple_form_for([@group, @event, @event_user]) do |f| %>
  <div class="form-group mb-3 mx-5 px-5">
      <%= f.association :user, label_method: :first_name, class: "form-control", placeholder: "Group name" %>
    <%= f.submit "Invite user", class: "btn btn-primary mb-3 w-100" %>
  </div>
  <% end %>
</div>

app/views/event_users/index.html.erb
<div class="container">
  <h1 class="dash-text text-center mt-3 mb-3" style="padding: 0; margin: 0;">My Events</h1>
  <div class="row mt-1">
    <% @events.reverse.each do |event| %>
      <div class="col-12 col-sm-6 col-xl-4 d-flex justify-content-center mb-4">
        <%= link_to group_event_path(event, event.group.id), style: "text-decoration: none;" do %>
          <div class="card-trip mb-4" style="height: 100%;">
            <% if event.event_photo.attached? %>
              <%= cl_image_tag event.event_photo.key, height: 200, width: 400 %>
            <% else %>
              <%= image_tag "background.jpg", height: 200, width: 400 %>
            <% end %>
            <div class="card-trip-infos">
              <% if event.group.user.photo.attached? %>
                <%= cl_image_tag event.group.user.photo.key, class: "card-trip-user avatar-bordered" %>
              <% else %>
                <img src="<%= asset_path "card-style-groups3.jpg" %>" alt=""class="card-trip-user avatar-bordered">
              <% end %>
            </div>
              <h3 class="text-center mt-3 larger-text" style="text-decoration: none; color: black;"><%= event.name %></h3>
              <div class="mt-2">
                <h6 class="text-center smaller-text" style="text-decoration: none; color: black;">Admin: <%= event.group.user.first_name.capitalize %></h6>
                <h6 class="text-center smaller-text" style="text-decoration: none; color: black;"><%= (UserGroup.where('group_id = ? AND status = ?', event.group.id, true).count) + (EventUser.where('event_id = ? AND status = ?', event.id, true).count) %> • attendees</h6>
                <div class="d-flex justify-content-center mt-3">
                  <% if current_user == event.group.user %>
                    <%= link_to group_path(event.group) do  %>
                      <i class="far fa-edit mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                    <%= link_to event_path(event), method: :delete do  %>
                      <i class="fas fa-trash-alt mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                  <% else %>
                    <%= link_to root_path do  %>
                      <i class="fas fa-trash-alt mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/event_users/new.html.erb
<%= render "form" %>