config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :events, only: %i[show new create update] do
      resources :messages, only: %i[create]
      resources :event_users, only: %i[new]
    end
    resources :usergroups, only: %i[new create destroy] do
      member do
        delete :kick
      end
    end
  end
  resources :events, only: %i[index destroy]
  resources :usergroups, only: %i[index] do
    member do
      put :accept
    end
  end
  resources :event_users, only: %i[index destroy create] do
    member do
      put :accept
    end
  end
  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end
  resources :friendships, only: %i[index destroy] do
    member do
      put :accept
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_notifications, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  validates :name, presence: true
  has_one_attached :photo
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @usergroups = UserGroup.where('user_id = ?', current_user.id).where('status = ?', true)
    @group = Group.new
  end

  def show
    if UserGroup.where('group_id = ? AND user_id = ?', params[:id].to_i, current_user.id).empty?
      redirect_to "/groups", alert: "Naughty, naughty...."
    end
    if Group.where('id = ?', params[:id]).empty?
      redirect_to "/groups"
    else
      @group = Group.find(params[:id])
      @usergroups = UserGroup.where('group_id = ? AND status = ?', @group.id, true)
      @pendingusers = UserGroup.where('group_id = ? AND status = ?', @group.id, false)
      @users = @usergroups.map do |ug|
        ug.user
      end
      @events = Event.where('group_id = ?', @group.id).reject { |event| event.end_date <= Date.today }
      @my_friendships = Friendship.where('friend_one_id = ? OR friend_two_id = ?', current_user.id, current_user.id)
    end
    @events = Event.where('group_id = ?', @group.id).reject { |event| event.end_date <= Date.today }
    @events_past = Event.where('group_id = ?', @group.id).reject { |event| event.end_date > Date.today }
    @usergroup = UserGroup.new
    @event = Event.new
    @my_friendships = Friendship.where('friend_one_id = ? OR friend_two_id = ?', current_user.id, current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(set_group)
    @group.user = current_user
    @usergroup = UserGroup.new
    @usergroup.user = current_user
    @usergroup.status = true
    if @group.save
      @usergroup.group = @group
      @usergroup.save!
      redirect_to "/groups/#{@group.id}"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(set_group)
    if @group.save
      redirect_to "/groups/#{@group.id}"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to "/groups"
  end

  private

  def set_group
    params.require(:group).permit(:name, :photo)
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group, html: { class: "nice-class"}) do |f| %>
<div class="form-group mb-3 mx-5 px-5">
    <%= f.input :name, class: "form-control", placeholder: "Group name" %>
    <%= f.input :photo, as: :file, input_html: { multiple: false }, label: "Attach a group photo" %>
  <%= f.submit "Create group", class: "btn btn-primary mb-3 w-100" %>
</div>
<% end %>

app/views/groups/edit.html.erb
<div class="form-container">
  <div class="update-form-card">
    <%= simple_form_for(@group) do |f| %>
    <div class="form-group">
        <%= f.input :name, class: "form-control", placeholder: "Group name" %>
      <%= f.submit "Update Group", class: "btn btn-primary mb-3 w-100" %>
    </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center mb-4">
    <button type="button" class="btn btn-ghost mb-0 mt-2" data-bs-toggle="modal" data-bs-target="#newGroup">New Group</button>
  </div>
  <div class="row mt-1">
    <% @usergroups.reverse.each do |group| %>
      <div class="col-12 col-sm-6 col-xl-4 d-flex mb-4 justify-content-center">
        <%= link_to group_path(group.group), style: "text-decoration: none;" do %>
          <div class="card-trip mb-4" style="height: 100%;">
            <% if group.group.photo.attached? %>
              <%= cl_image_tag group.group.photo.key, height: 200, width: 400 %>
            <% else %>
              <%= image_tag "background.jpg", height: 200, width: 400 %>
            <% end %>
            <div class="card-trip-infos">
              <% if group.group.user.photo.attached? %>
                <%= cl_image_tag group.group.user.photo.key, class: "card-trip-user avatar-bordered" %>
              <% else %>
                <img src="<%= asset_path "card-style-groups3.jpg" %>" alt="" class="card-trip-user avatar-bordered">
              <% end %>
            </div>
              <h3 class="text-center mt-3 larger-text" style="text-decoration: none; color: black;"><%= group.group.name %></h3>
              <div class="mt-2">
                <h6 class="text-center smaller-text" style="text-decoration: none; color: black;">Admin: <%= group.group.user.first_name.capitalize %></h6>
                <h6 class="text-center smaller-text" style="text-decoration: none; color: black;"><%= UserGroup.where('group_id = ?', group.group.id).count %> • members</h6>
                <div class="d-flex justify-content-center mt-3">
                  <% if current_user == group.group.user %>
                    <%= link_to edit_group_path(group.group) do  %>
                      <i class="far fa-edit mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                    <%= link_to group_path(group.group), method: :delete do  %>
                      <i class="fas fa-trash-alt mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                  <% else %>
                    <%= link_to group_usergroup_path(group.group, group), method: :delete do  %>
                      <i class="fas fa-trash-alt mx-3" style="color: black; font-size: 20px;"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<div class="container mb-5 p-0">
  <div class="modal fade" id="newGroup" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="newGroupForm" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class data-open-form-target="form"  class="modal-body">
          <%= render "form", group: @group%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container d-flex justify-content-center">
  <%= render "form" %>
</div>

app/views/groups/show.html.erb
<!-- <div class="container pt-3">
  <%= link_to "all groups", groups_path, class: "btn btn-danger" %>
  <h1><%= @group.name %></h1>
  <br>
  <h3>Admin: <%= @group.user.first_name %></h3>
  <br>
  <h3>Group Members</h3>
  <% @users.each do |user| %>
    <h4><%= user.first_name %></h4>
  <% end %>
  <% @events.each do |event| %>
    <h3><%= link_to event.name, group_event_path(event), class: "btn btn-danger" %></h3>
  <% end %>
  <%= link_to "Add group members", new_group_usergroup_path(@group), class: "btn btn-danger" %>
  <%= link_to "Create new group event", new_group_event_path(@group), class: "btn btn-danger" %>
  <% if @group.user == current_user %>
    <%= link_to "Edit group name", edit_group_path(@group), class: "btn btn-danger" %>
    <%= link_to "Destroy Group", group_path(@group), method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>
-->

<div class="container mb-5 mt-3">
  <div class="row container">
    <div class="col-12 col-xl-4">
      <div class="card-trip pb-3">
        <% if @group.photo.attached? %>
          <%= cl_image_tag @group.photo.key %>
        <% else %>
          <%= image_tag "background.jpg" %>
        <% end %>
        <div class="card-trip-infos">
          <% if @group.user.photo.attached? %>
            <%= cl_image_tag @group.user.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
            <img src="<%= asset_path "card-style-groups3.jpg" %>" alt=""class="card-trip-user avatar-bordered">
          <% end %>
        </div>
          <h3 class="text-center mt-3 larger-text"><%= @group.name %></h3>
          <div class="mt-2">
            <h6 class="text-center smaller-text">Admin: <%= @group.user.first_name.capitalize %></h6>
            <h6 class="text-center smaller-text"><%= UserGroup.where('group_id = ?', @group.id).count %> • members</h6>
            <div class="d-flex justify-content-center mt-3">
              <%= link_to edit_group_path(@group) do  %>
                <i class="far fa-edit mx-3" style="color: black; font-size: 20px;"></i>
              <% end %>
              <%= link_to group_path(@group), method: :delete do  %>
                <i class="fas fa-trash-alt mx-3" style="color: black; font-size: 20px;"></i>
              <% end %>
            </div>
          </div>
      </div>
      <div class="card-trip mt-3 p-3 mb-3" style=" height: auto;">
        <h5 class="p-3 larger-text">Members</h5>
        <div style="height: 200px; overflow: scroll;">
          <% @users.sort_by { |u| u.created_at }.reverse.each do |user| %>
            <h6 class="m-2 d-flex align-items-center">
              <div>
                <% if user.photo.attached? %>
                  <% if user == @group.user %>
                    <%= cl_image_tag user.photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                  <% else %>
                    <%= cl_image_tag user.photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                  <% end %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                <% end %>
              </div>
              <div class="ms-3 d-flex justify-content-between">
                <div class="mt-1 smaller-text">
                  <%= user == current_user ? "You" : user.first_name %>
                  <%= user == @group.user ? " -   Admin" : "" %>
                </div>
                <% if user != current_user %>
                  <% if Friendship.where('friend_one_id = ? OR friend_two_id = ?', user.id, user.id).select { |f| @my_friendships.include? f }.empty? %>
                    <%= link_to "Add friend", user_friendships_path(current_user, user), method: :post, class: "btn btn-primary btn-sm ml-3 ms-3" %>
                  <% end %>
                  <% if current_user == @group.user %>
                    <%= link_to kick_group_usergroup_path(@group, user), method: :delete, style: "color: red;", class: "ms-3 mt-1" do%>
                      <i class="fas fa-ban"></i>
                    <% end %>
                  <% end %>
                <% end %>
            </h6>
          <% end %>
              </h6>
          <% @pendingusers.each do |user| %>
              <h6 class="m-2 d-flex align-items-center">
                <% if user.user.photo.attached? %>
                  <%= cl_image_tag user.user.photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                <% end %>
                <div class="ms-3 smaller-text"><%= user.user == current_user ? "You" : user.user.first_name %> - pending</div>
                </p>
              </h6>
          <% end %>
        </div>
        <%= simple_form_for @usergroup, url: group_usergroups_path(@group)  do |f| %>
          <div class="form-group text-center">
            <%= f.association :user, collection: current_user.user_group_invites(@group), label_method: :first_name, method: :post, input_html: {multiple: true, data: {controller: 'select2', select2_options_value: {tags: true}}}, placeholder: "Add your friends", label: "Select friends to add" %>
          <%= f.submit "Invite Friends", class: "btn btn-primary w-100" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-xl-8">
      <div class="card-trip px-4 py-3" style="">
        <h3 class="text-center larger-text">Events   <%= link_to new_group_event_path(@group) do  %>
            <i class="fas fa-plus" style="font-size: 22px; color: black;"></i>
            <% end %></h3>
        <div class="row">
          <% @events.each do |event| %>
          <%= link_to group_event_path(event), style: "text-decoration: none; color: white;" do %>
            <div class="card-product mb-4">
              <% if event.event_photo.attached? %>
                <%= cl_image_tag event.event_photo.key %>
              <% else %>
                <img src="<%= asset_path "background.jpg" %>" alt="">
              <% end %>
              <div class="card-product-infos d-flex justify-content-between h-100 w-100">
                <div class="card-name pt-3">
                  <h2 class="larger-text text-black"><%= event.name.capitalize %></h2>
                  <h6 style="color: black;" class="smaller-text"><%= event.location %></h6>
                </div>
                <div class="card-date d-flex align-items-end">
                  <h6 style="color: black;" class="mb-0 smaller-text"><%= event.start_date.strftime("%A, %b %d") %> - <%= event.end_date.strftime("%A, %b %d") %>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if @events_past.length > 0 %>
      <div class="col-12 col-xl-8 w-100 mt-3">
        <div class="card-trip px-4 py-3" style="">
          <h3 class="text-center larger-text">Past Events</h3>
          <div class="row">
            <% @events_past.each do |event| %>
              <div class="col-12 col-xl-6">
                <%= link_to group_event_path(event), style: "text-decoration: none; color: white;" do %>
                  <div class="card-product justify-content-center rounded mb-1 mt-3" style="height: 120px; background-color: #F4B658;">
                    <div class="card-product-infos text-center">
                      <h2 class="mb-2 smaller-text"><%= event.name.capitalize %></h2>
                      <h6 style="color: white;" class="smaller-text"><%= event.location %></h6>
                      <h6 style="color: white;" class="mb-2 smaller-text"><%= event.start_date.strftime("%A, %b %d")
 %> - <%= event.end_date.strftime("%A, %b %d") %></h6>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<% if @events_past != nil && @events_past.length > 0 %>

<% end %>

<div class="container" data-controller="open-form">
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class data-open-form-target="form" class="modal-body">
          <%= render "usergroups/form", usergroup: @usergroup, group: @group%>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class data-open-form-target="form" class="modal-body">
          <%= render "events/form", event: @event, group: @group%>
        </div>
      </div>
    </div>
  </div>