config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :events, only: %i[show new create update] do
      resources :messages, only: %i[create]
      resources :event_users, only: %i[new]
    end
    resources :usergroups, only: %i[new create destroy] do
      member do
        delete :kick
      end
    end
  end
  resources :events, only: %i[index destroy]
  resources :usergroups, only: %i[index] do
    member do
      put :accept
    end
  end
  resources :event_users, only: %i[index destroy create] do
    member do
      put :accept
    end
  end
  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end
  resources :friendships, only: %i[index destroy] do
    member do
      put :accept
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :friend_one_id
  belongs_to :user, class_name: 'User', foreign_key: :friend_two_id

  def friend_one
    User.find(friend_one_id)
  end

  def friend_two
    User.find(friend_two_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendship_requests = Friendship.where('friend_two_id = ? AND confirmed = ?', current_user.id, false)
    @friendships_notaccepted = Friendship.where('friend_two_id = ? OR friend_one_id = ?', current_user.id, current_user.id)
    if @friendships_notaccepted.length.positive?
      @friendships = @friendships_notaccepted.select { |fs| fs.confirmed == true }
      @friendships_pending = @friendships_notaccepted.select { |fs| fs.confirmed == false }
    end
    if @friendships && @friendships.length.positive?
      @two_is_friends = @friendships.select { |f| f.friend_one_id == current_user.id } # friend_two_id is friend
      @one_is_friends = @friendships.select { |f| f.friend_two_id == current_user.id } # friend_one_id is friend
    end
    @friendship = Friendship.new
  end

  def show
  end

  def create
    @friendship = Friendship.new
    if params[:format]
      @friendship.friend_one_id = current_user.id
      @friendship.friend_two_id = User.find(params[:format]).id
      @friendship.save
    elsif params[:user_id] != current_user.id
      friend_ids = params[:friendship][:friend_two_id].select { |id| id != "" }
      friend_ids.each do |id|
        @friendship = Friendship.new
        @friendship.friend_one_id = current_user.id
        @friendship.friend_two_id = User.find(id).id
        @friendship.save
      end
    else
      @friendship.friend_one_id = current_user.id
      @friendship.friend_two_id = User.find(params[:user_id]).id
      @friendship.save!
    end
    redirect_to "/"
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    redirect_to "/"
  end

  def accept
    @friendship = Friendship.find(params[:id])
    @friendship.confirmed = true
    @friendship.save
    redirect_to "/"
  end
end

app/views/friendships/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-xl-4">
      <div class="card-trip mt-3 p-3" style="border-radius: 15px; height: auto;">
        <h4 class="text-center">Your friends</h4>
        <% if @two_is_friends %>
          <% @two_is_friends.each do |f| %>
            <div class="d-flex my-3 justify-content-between">
              <div class="d-flex">
                <% if User.find(f.friend_two_id).photo.attached? %>
                  <%= cl_image_tag User.find(f.friend_two_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                <% end %>
                <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(f.friend_two_id).first_name %></h6>
              </div>
              <%= link_to "DESTROY!!!", friendship_path(f), method: :delete, class: "btn btn-danger" %>
            </div>
          <% end %>
        <% end %>
        <% if @one_is_friends %>
          <% @one_is_friends.each do |f| %>
            <div class="d-flex my-3 justify-content-between">
              <div class="d-flex">
                <% if User.find(f.friend_one_id).photo.attached? %>
                  <%= cl_image_tag User.find(f.friend_one_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                <% end %>
                <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(f.friend_one_id).first_name %></h6>
              </div>
              <%= link_to "DESTROY!!!", friendship_path(f), method: :delete, class: "btn btn-danger" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-xl-4">
      <div class="card-trip mt-3 p-3" style="border-radius: 15px; height: auto;">
        <h4 class="text-center">Accept/Decline Requests</h4>
        <% @friendship_requests.each do |friendship| %>
          <div class="d-flex my-3 justify-content-between">
            <div class="d-flex">
              <% if User.find(friendship.friend_one_id).photo.attached? %>
                <%= cl_image_tag User.find(friendship.friend_one_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
              <% else %>
                <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
              <% end %>
              <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(friendship.friend_one_id).first_name %></h6>
            </div>
            <%= link_to "Accept", accept_friendship_path(friendship), method: :put, class: "btn btn-danger" %>
            <%= link_to "Decline", friendship_path(friendship), method: :delete, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-xl-4">
      <div class="card-trip mt-3 p-3" style="border-radius: 15px; height: auto;">
        <h4 class="text-center">Send friend requests</h4>
        <% if @friendships_pending %>
          <% @friendships_pending.each do |f| %>
            <% if User.find(f.friend_one_id) == current_user %>
              <div class="d-flex my-3 justify-content-between">
                <div class="d-flex">
                  <% if User.find(f.friend_two_id).photo.attached? %>
                    <%= cl_image_tag User.find(f.friend_two_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                  <% else %>
                    <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                  <% end %>
                  <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(f.friend_two_id).first_name %> - (pending)</h6>
                </div>
                <%= link_to "DESTROY!!!", friendship_path(f), method: :delete, class: "btn btn-danger" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <%= render "form", class: "w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/friendships/show.html.erb
<div class="container">
  <div class="card-trip mt-3 p-3" style="border-radius: 15px; height: auto;">
    <% @friendships.each do |friendship| %>
      <% if User.find(friendship.friend_one_id).photo.attached? %>
        <%= cl_image_tag User.find(friendship.friend_one_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
      <% else %>
        <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
      <% end %>
      <p><%= User.find(friendship.friend_one_id).first_name.capitalize %> has sent you a friend request!</p>
      <%= link_to "Accept", accept_user_friendship_path(current_user.id, friendship.id), method: :put, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>