config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :events, only: %i[show new create update] do
      resources :messages, only: %i[create]
      resources :event_users, only: %i[new]
    end
    resources :usergroups, only: %i[new create destroy] do
      member do
        delete :kick
      end
    end
  end
  resources :events, only: %i[index destroy]
  resources :usergroups, only: %i[index] do
    member do
      put :accept
    end
  end
  resources :event_users, only: %i[index destroy create] do
    member do
      put :accept
    end
  end
  resources :users, only: %i[show] do
    resources :friendships, only: %i[create]
  end
  resources :friendships, only: %i[index destroy] do
    member do
      put :accept
    end
  end
end

app/views/pages/_form.html.erb
<%= simple_form_for @friendship, url: user_friendships_path(current_user)  do |f| %>
<div class="form-group d-flex flex-column align-items-center mt-5 w-100">
    <%= f.association :user, collection: current_user.friend_invites, method: :post, label_method: :first_name, input_html: {multiple: true, data: {controller: 'select2', select2_options_value: {tags: true}}}, placeholder: "Add your friends", class: "w-100", label: "" %>
  <%= f.submit "Send friend requests", class: "btn btn-primary btn-sm ms-2 send-button" %>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="home-page-background-top" style="height: 100%;">
  <% if user_signed_in? %>
    <div class="container pb-5">
      <div class="row mb-5 py-5">
        <div class="col-12 d-flex  flex-column justify-content-center">
          <h1 class="dash-text text-center" style="margin: 30px 0 10px 0; text-decoration: none; font-size: 50px;">Hello, <%= current_user.first_name.capitalize %></h1>
          <h6 class="landing-page-text text-center" style="margin-bottom: 30px; font-size: 20px; padding: 0 21px;">Welcome to your dashboard, from here you can access all your groups, events and invitations. To get started with an event go ahead into your group and create the event you want to from there!</h6>
          <% if current_user.groups.empty? %>
            <div class="d-flex justify-content-center">
              <%= link_to "Create your first group", new_group_path, class: "btn btn-ghost", style: "" %>
            </div>
          <% else %>
            <div class="d-flex justify-content-center">
              <%= link_to "See your groups", groups_path, class: "btn btn-ghost", style: "font-size: 17px;" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row px-5 d-flex justify-content-center">
        <div class="col-12 col-sm-6 col-xl-5 d-flex flex-column justify-content-center">
          <%= link_to event_users_path, style: "text-decoration: none;" do %>
            <div class="card-trip" style="height: 350px;">
              <%= image_tag "events-card.jpg", style: "height: 280px" %>
              <div>
                <h6 class="text-center dash-text" style="margin: 15px 0px 8px 0px; text-decoration: none;">Events</h6>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-sm-6 col-xl-7 d-flex flex-column justify-content-center">
          <div>
            <p class="landing-page-text text-start ps-5 pe-0" style="margin: 0px 0px 10px 0px">Take a look at your past events and see what your friends have uploaded to the photos section to reminisce on all the great events you've been to with your friends.</p>
          </div>
        </div>
      </div>
      <div class="row px-5 mt-5 d-flex justify-content-center">
        <div class="col-12 col-sm-6 col-xl-7 d-flex flex-column justify-content-center">
          <div>
            <p class="landing-page-text text-start ps-5 pe-0" style="margin: 0px 0px 10px 0px">Here is where you can create your friendship groups simply by adding the from your friends list. Groups are a great way of organising your circles and creating events through the groups page.</p>
          </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-5 d-flex flex-column justify-content-center">
          <%= link_to  groups_path, style: "text-decoration: none;" do %>
            <div class="card-trip" style="height: 350px;">
              <%= image_tag "card-style-home-group.jpg", style: "height: 280px" %>
              <div>
                <h6 class="text-center dash-text" style="margin: 15px 0px 8px 0px; text-decoration: none;">Groups</h6>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      </div>
    </div>
    <%# OFF CANVAS %>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasWithBackdropFriends" aria-labelledby="offcanvasWithBackdropLabelFriends">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title larger-text" id="offcanvasWithBackdropLabel"></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body smaller-text">
        <h4 class="text-center larger-text">Your Friends</h4>
        <% if @two_is_friends %>
          <% @two_is_friends.each do |f| %>
            <div class="d-flex my-3 justify-content-between">
              <div class="d-flex ps-3">
                <% if User.find(f.friend_two_id).photo.attached? %>
                  <%= cl_image_tag User.find(f.friend_two_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 50px;" %>
                <% end %>
                <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(f.friend_two_id).first_name %></h6>
              </div>
              <%= link_to friendship_path(f), method: :delete do %>
                <i class="fas fa-ban mt-3 me-5" style="color: red;"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <% if @one_is_friends %>
          <% @one_is_friends.each do |f| %>
            <div class="d-flex my-3 justify-content-between">
              <div class="d-flex ps-3">
                <% if User.find(f.friend_one_id).photo.attached? %>
                  <%= cl_image_tag User.find(f.friend_one_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                <% else %>
                  <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 60px;" %>
                <% end %>
                <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(f.friend_one_id).first_name %></h6>
              </div>
              <%= link_to friendship_path(f), method: :delete do %>
                <i class="fas fa-ban mt-3 me-5" style="color: red;"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <% if @friendship_requests.size > 0 %>
          <h4 class="text-center larger-text">Accept/Decline Requests</h4>
        <% end %>
        <% @friendship_requests.each do |friendship| %>
          <div class="d-flex my-3 justify-content-between">
            <div class="d-flex ps-3">
              <% if User.find(friendship.friend_one_id).photo.attached? %>
                <%= cl_image_tag User.find(friendship.friend_one_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
              <% else %>
                <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 60px;" %>
              <% end %>
              <h6 class="ms-3 mt-3" style="color: black;"><%= User.find(friendship.friend_one_id).first_name %></h6>
            </div>
            <%= link_to accept_friendship_path(friendship), method: :put do %>
              <i class="fas fa-check mt-3 me-5" style="color: green;"></i>
            <% end %>
            <%= link_to friendship_path(friendship), method: :delete do %>
              <i class="fas fa-ban mt-3 me-5" style="color: red;"></i>
            <% end %>
          </div>
        <% end %>
        <h4 class="text-center larger-text">Send friend requests</h4>
        <% if @friendships_pending %>
          <% @friendships_pending.each do |f| %>
            <% if User.find(f.friend_one_id) == current_user %>
              <div class="d-flex my-3 justify-content-between">
                <div class="d-flex ps-3">
                  <% if User.find(f.friend_two_id).photo.attached? %>
                    <%= cl_image_tag User.find(f.friend_two_id).photo.key, class: "avatar", style: "height: 50px; width: 50px;" %>
                  <% else %>
                    <%= image_tag "unknown-avatar.png", class: "avatar", style: "height: 50px; width: 60px;" %>
                  <% end %>
                  <h6 class="ms-1 mt-3" style="color: black;"><%= User.find(f.friend_two_id).first_name %> - (pending)</h6>
                </div>
                <%= link_to friendship_path(f), method: :delete do %>
                  <i class="fas fa-ban mt-3 me-5" style="color: red;"></i>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <%= render "form", class: "w-100" %>
      </div>
    </div>
    <%# OFF CANVAS %>
    <%# OFF CANVAS - INVITES START %>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body" style="overflow: auto;">
        <% if (@invitations.size + @eventinvitations.size) == 0 %>
          <h3 class="larger-text text-center">All Clear</h3>
        <% end %>
          <% if @invitations.size > 0 %>
            <h3 class="larger-text text-center">Group Invitations</h3>
            <% @invitations.reverse.each do |invitation| %>
              <div class="card-trip">
                <% if invitation.group.photo.attached? %>
                  <%= cl_image_tag invitation.group.photo.key %>
                <% else %>
                  <%= image_tag "background.jpg" %>
                <% end %>
                <div class="card-trip-infos text-center d-flex justify-content-center mb-0">
                  <div>
                    <h2 class="larger-text my-1 mt-0" style="font-size: 25px;"><%= invitation.group.name %></h2>
                    <p class="smaller-text my-1 mb-0" style="font-size: 15px;"><%= invitation.group.user.first_name %> has invited you!</p>
                  </div>
                </div>
                <div class="d-flex justify-content-around mt-0">
                  <%= link_to accept_usergroup_path(invitation), method: :put do %>
                    <i class="fas fa-check mt-0 mb-3" style="color: green;"></i>
                  <% end %>
                  <%= link_to group_usergroup_path(invitation.group, invitation), method: :delete do %>
                    <i class="fas fa-ban mt-0 mb-3" style="color: red;"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
          <% if @eventinvitations.size > 0 %>
            <h3 class="larger-text text-center mt-3 mb-1">Event Invitations</h3>
            <% @eventinvitations.reverse.each do |invitation| %>
              <div class="card-trip">
                <% if invitation.event.event_photo.attached? %>
                  <%= cl_image_tag invitation.event.event_photo %>
                <% else %>
                  <%= image_tag "background.jpg" %>
                <% end %>
                <div class="card-trip-infos text-center d-flex justify-content-center mb-0">
                  <div>
                    <h2 class="larger-text my-1 mt-0" style="font-size: 25px;"><%= invitation.event.name %></h2>
                    <p class="smaller-text my-1 mb-0" style="font-size: 15px;">Held by group: <%= invitation.event.group.name %></p>
                    <p class="smaller-text my-1 mb-0" style="font-size: 15px;"><%= invitation.event.start_date %> to <%= invitation.event.end_date %></p>
                  </div>
                </div>
                <div class="d-flex justify-content-around mt-0">
                  <%= link_to accept_event_user_path(invitation), method: :put do %>
                    <i class="fas fa-check mt-0 mb-3" style="color: green;"></i>
                  <% end %>
                  <%= link_to event_user_path(invitation.event, invitation), method: :delete do %>
                    <i class="fas fa-ban mt-0 mb-3" style="color: red;"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%# INVITES END %>
   <% else %>
    <div style="background-image: url(<%= asset_path "background.jpg" %>)" class="background-landing">
      <div class="frame">
        <h1 class="landing-page-title">Welcome to Where2!</h1>
        <p  class="landing-page-text" style="padding: 0 550px;"></p>
        <%= link_to new_user_registration_path do %>
          <div class="button-landing-sign">
            <span style="color: white;">Sign up</span>
            <svg>
            <polyline class="o1" points="0 0, 150 0, 150 55, 0 55, 0 0"></polyline>
            <polyline class="o2" points="0 0, 150 0, 150 55, 0 55, 0 0"></polyline>
          </svg>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
 </div>
</div>